baseURL = "https://wangzhr.top"
languageCode = "en-us"
title = "RAMDOM THOUGHTS"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "RAMDOM THOUGHTS"
  homepage = "http://localhost:1313/about/"

# [languages]
#  [languages.en]
#    contentDir = "content/en"
#    languageName = "English"
#    weight = 1
#  [languages.cn]
#    contentDir = "content/cn"
#    languageName = "Chinese"
#    weight = 1

[params]
# disqus = "joway" # disqus account name 
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/index.html"

# [[params.socials]]
# name = "Tags"
# link = "/tags/index.html"

# [[params.socials]]
# name = "Daily"
# link = "/daily/index.html"
