baseURL = "https://wangzhr.top/"
languageCode = "en-us"

title = "Pseudowang"

theme = "yinyang"
DefaultContentLanguage = "cn"


# [outputs]
#   home = ["HTML", "RSS", "JSON"]

# [languages]
#  [languages.en]
#    contentDir = "content/en"
#    languageName = "English"
#    weight = 1
#  [languages.cn]
#    contentDir = "content/cn"
#    languageName = "Chinese"
#    weight = 1

[params]
# disqus = "joway" # disqus account name 
extraHead = ''
favicon = "/images/avatar.png"
name = "pseudowang"
mainSections = ["posts", "daily", "notes" ]
description = "记录无用却有趣的事物"
# cusdis = true 
disqus = 'pseudowang' 

[[params.author]]
name = "pseudowang"
homepage = "https://wangzhr.top/about"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/index.html"

# [[params.socials]]
# name = "Tags"
# link = "/tags/index.html"

[[params.socials]]
name = "Life"
link = "/daily/index.html"